### ISSUE TITLE
Downloading the HMDA data

### ISSUE THREAD

**Issue by SantoshSrinivas79** [cfpb/qu#165]
Is there a way to create a torrent to allow downloading the data more effectively for offline analysis. I am trying to download the entire data available at [The Home Mortgage Disclosure Act - Explore](http://www.consumerfinance.gov/hmda/explore)

The data is about 72.3 GB. There is absolutely no way of downloading it. The download times out and fails through a download manager too.

Please advise.

**Comment by SantoshSrinivas79** [comment]
@cndreisbach Would it be possible to upload the archives through 2013-2015 as above?

**Comment by marcesher** [comment]
@SantoshSrinivas79 You can download a zip file for each individual year by going to http://www.consumerfinance.gov/data-research/hmda/explore, and in the "Filter" box, select the single year you wish to download. Then, toward the bottom of the screen, click the Download button. Repeat for all years in question.

There's logic under the hood that routes single-year, full-dataset requests directly to a zip file without querying from the API

<img width="1042" alt="download_hmda" src="https://cloud.githubusercontent.com/assets/127017/20970275/c34e038c-bc5a-11e6-978c-a9a928d8b0ed.png">

**Comment by SantoshSrinivas79** [comment]
@marcesher Thank you sir!

**Comment by SantoshSrinivas79** [comment]
@marcesher Is there way to do the same for this dataset too? [Consumer Complaint Database > Consumer Financial Protection Bureau](http://www.consumerfinance.gov/data-research/consumer-complaints/#download-the-data)

An s3 zip would be great!
