### ISSUE TITLE
CSV export fails for specific respondent_id and state_code

### ISSUE THREAD

**Issue by tyrauber** [cfpb/qu#255]
CSV export on api.consumerfinance.gov fails for specific where attributes, resulting in Failed - Network error (EOF).  It appears to be just one respondent_id and state_code for 2015 data, but I've replicated the issue in both [Explore the data](http://www.consumerfinance.gov/data-research/hmda/explore#!/as_of_year=2015&state_code-1=17&respondent_id=0000817824&section=filters) (Include labels and codes) and the [API html interface](https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html?%24select=&%24where=%28as_of_year%3D2015+AND+state_code%3D17+AND+respondent_id%3D%220000817824%22%29&%24group=&%24orderBy=&%24offset=0&%24format=html) (Output Format CSV).

```(as_of_year=2015 AND state_code=17 AND respondent_id="0000817824")```

[Failing API Call](https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$where=(as_of_year%3D2015+AND+state_code%3D17+AND+respondent_id%3D%220000817824%22)&$limit=0&$offset=0)
[https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$where=(as_of_year%3D2015+AND+state_code%3D17+AND+respondent_id%3D%220000817824%22)&$limit=0&$offset=0](https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$where=(as_of_year%3D2015+AND+state_code%3D17+AND+respondent_id%3D%220000817824%22)&$limit=0&$offset=0)

**Comment by sephcoster** [comment]
Thanks for the report Ty - we'll take a look!

**Comment by sleitner** [comment]
Yes, we very much appreciate the bug report! Until we get this fixed, note that results can be successfully obtained in json and xml formats. Thanks for bearing with us in the meantime.

**Comment by sleitner** [comment]
Fixed with an nginx change. This looks like it helped us close out a very old bug, so thanks again for the report @tyrauber.

**Comment by tyrauber** [comment]
Confirmed!  Thanks for the prompt fix.  Excellent API, btw, really well done.
