### ISSUE TITLE
Confused about HMDA API

### ISSUE THREAD

**Issue by chrismp** [cfpb/qu#259]
Hey everyone,I've been reading the docs for the CFPB's Home Mortgage Disclosure Act's API, but I'm confused about how to send requests for certain data types. For example, what type of call do i send when requesting the number of home refi loans for each county? And do I need an API key?

**Comment by contolini** [comment]
Hi @chrismp. No API key is needed. You can view the `hmda_lar` dataset over at [api.consumerfinance.gov](https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html).

With your example, here are all [refis grouped by county](https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html?%24select=county_name%2CCOUNT%28%29&%24where=loan_purpose_name%3D%22Refinancing%22&%24group=county_name&%24orderBy=county_name&%24offset=0&%24format=html) and here's the same query with only [Florida counties](https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html?%24select=county_name%2CCOUNT%28%29&%24where=loan_purpose_name%3D%22Refinancing%22+AND+state_name%3D%22Florida%22&%24group=county_name&%24orderBy=county_name&%24offset=0&%24format=html). You can receive the response in JSON or CSV by changing the output format radio button.

If you're exploring HMDA data, I recommend checking out the explorer: https://www.consumerfinance.gov/data-research/hmda/explore. One trick is to filter the data using the explorer and then view Chrome's network activity to see the API call it's making to api.consumerfinance.gov. You can then use that request URL in your own application. Replace `hmda_lar.jsonp` with `hmda_lar.[json|csv|html]` in the URL to get the data in different formats.

![screen shot 2018-04-05 at 8 13 28 pm](https://user-images.githubusercontent.com/1060248/38397855-ee9b1878-390d-11e8-950d-54d5386a3632.png)

**Comment by contolini** [comment]
You can concat the `state_code` and `county_code` fields to get the FIPS (after left padding them with zeros).

https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html?%24select=county_name%2Cstate_name%2Cstate_code%2Ccounty_code%2CCOUNT%28%29&%24where=loan_purpose_name%3D%22Refinancing%22&%24group=county_name%2Cstate_name%2Cstate_code%2Ccounty_code&%24orderBy=state_name%2Ccounty_name&%24offset=0&%24format=html

**Comment by chrismp** [comment]
Thanks again! By the way, if I want only data for calendar year 2016, do I specify that in the "where" clause with `as_of_year=2016`?
