### ISSUE TITLE
Querying for non-HTML download retrieves only 100 rows, even when I don't specify a limit

### ISSUE THREAD

**Issue by chrismp** [cfpb/qu#260]
This query for data from all Census tracts gets a CSV file with only 100 rows of data. https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$select=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name%2C+SUM(population)%2C+COUNT()&$where=as_of_year%3D2016&$group=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name&$orderBy=state_code%2C+county_code%2C+census_tract_number&$offset=0

Any idea how to fix this so I can download all the data for every tract? 

Web API link: https://api.consumerfinance.gov/data/hmda/slice/hmda_lar.html?%24select=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name%2C+SUM%28population%29%2C+COUNT%28%29&%24where=as_of_year%3D2016&%24group=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name&%24orderBy=state_code%2C+county_code%2C+census_tract_number&%24offset=&%24format=html

**Comment by chrismp** [comment]
I entered `0` to get all records, but instead got a CSV with just headers and no rows of data: https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$select=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name%2C+SUM(population)%2C+COUNT()&$where=as_of_year%3D2016&$group=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name&$orderBy=state_code%2C+county_code%2C+census_tract_number&$limit=0&$offset=0

**Comment by chrismp** [comment]
It appears the maximum number one can set for `limit` is a bit above 199500.

**Comment by marcesher** [comment]
This appears to be a limitation of the API. Likely `limit` and `offset` should simply not be supported for aggregation queries such as this one. I recommend removing limit and offset, which will then fetch all the rows for the aggregation.
