### ISSUE TITLE
Offset limit; 400 error

### ISSUE THREAD

**Issue by chrismp** [cfpb/qu#261]
I tried running a query to find the number of home loans, for each type, for each Census tract. I asked for a `limit` of 15000 with `offset` set to 100000. I got an `HTTP ERROR 400`.

https://api.consumerfinance.gov:443/data/hmda/slice/hmda_lar.csv?$select=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name%2C+SUM(population)%2C+COUNT()&$where=as_of_year%3D2016&$group=state_code%2C+county_code%2C+census_tract_number%2C+loan_purpose_name&$orderBy=state_code%2C+county_code%2C+census_tract_number&$limit=150000&$offset=100000

**Comment by marcesher** [comment]
I believe this is a limitation in the API. It likely should just not support `limit` and `offset` in aggregation queries such as the one you're running.

To get that query above to work, I recommend you remove limit and offset, get the full data set, and then paginate locally if you need to.
